---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: "13.6.4"
  provider: virtualbox
  use_vagrant_berkshelf_plugin: true

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :disabled

platforms:
  - name: centos-7.3
suites:
  - name: default
    run_list:
      - recipe[tdd-box::default]
    attributes:
