---
driver:
  name: dokken
  privileged: true
  chef_version: latest # or 15 or 15.0 or 15.0.300 or curent

transport:
  name: dokken

provisioner:
  name: dokken
  install_strategy: once

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7
  driver_config:
    pid_one_command: /usr/sbin/init
    privileged: true
    provision_command:
      - systemctl enable sshd.service


suites:
  - name: default
    run_list:
    - recipe[tdd-box::default]