---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: "13.6.4"
  provider: virtualbox
  use_vagrant_berkshelf_plugin: true

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :disabled

platforms:
  - name: centos-7.3
suites:
  - name: default
    run_list:
      - recipe[tdd-box::default]
    attributes:

verifier:
  name: inspec
  inspec_tests:
    - name: InspecTests
      # url: https://public-github-repo/user-name/repo-name/archive/master.zip
      path: test/integration/default
    